services:
  db:
    image: mysql:8.4
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
#      - MYSQL_ROOT_HOST=%
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_USER=resume_user
#      - MYSQL_PASSWORD=resume_password
      - MYSQL_DATABASE=resume_manager_db
      - MYSQL_TCP_PORT=3307
#    volumes:
#      - "./conf.d:/etc/mysql/conf.d:ro"
    command: mysqld --mysql_native_password
    healthcheck:
       test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
       timeout: 2s
       retries: 10
#    profiles:
#      - mysql
    networks:
      - my_network
        
  web-app:
    depends_on:
       db:
         condition: service_healthy
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - MYSQL_URL=jdbc:mysql://db:3307/mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my_root_pwd
#    volumes:
#      - .:/app
    networks:
      - my_network

networks:
  my_network:
    driver: bridge  